joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 5  # Reduced to 5 Hz for less load

velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel'
  right_wheel: 'right_wheel'
  publish_rate: 20  # Reduced to 20 Hz (was 30)
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  wheel_separation: 0.35
  wheel_radius: 0.05
  enable_odom_tf: true
  publish_cmd: true
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier: 1.0
  cmd_vel_timeout: 1.0
  base_frame_id: base_link
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0
      min_velocity: -0.5
      has_acceleration_limits: true
      max_acceleration: 0.2
      min_acceleration: -0.2
      has_jerk_limits: true
      max_jerk: 5.0
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 0.5
      has_jerk_limits: true
      max_jerk: 2.5
