local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.3

  static_map: false  
  rolling_window: true
  width: 20
  height: 100
  resolution: 0.07

  # Plugins (common layers for local costmap)
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # Obstacle Layer parameters
  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      min_range: 0.3
      max_range: 5.0
      observation_persistence: 0.0
      raytrace_range: 3.0
      sensor_frame: lidar_link

  # Inflation Layer parameters
  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0